apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-resume
  labels:
    app: resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      securityContext:
        runAsUser: 101
      containers:
      - name: resume
        image: mubarakbunza/resume-prod:latest
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "32Mi"
          limits:
            cpu: "250m"
            memory: "64Mi"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          
---
apiVersion: v1
kind: Service
metadata:
  name: my-resume
spec:
  selector:
    app: resume
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: http