FROM node:15.12.0-alpine as builder

ENV NODE_ENV prod

WORKDIR /app
COPY package.json .
RUN npm install

COPY . .
RUN npm run build


FROM nginxinc/nginx-unprivileged:stable-alpine
COPY --from=builder --chown=101:101 /app/build/ /usr/share/nginx/html

COPY --chown=101:101 nginx.conf /etc/nginx/conf.d/default.conf
