version: "3.8"

services:
  resume-dev:
    container_name: resume-dev
    image: resume-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000