FROM node:15.12.0-alpine as builder

RUN adduser -D new_guest
USER new_guest

ENV NODE_ENV prod

WORKDIR /app
COPY package.json .
RUN npm install

COPY . .
RUN npm run build


FROM nginx:stable-alpine
COPY --from=builder /app/build/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]